### ISSUE TITLE
Incompatible with Idea2024.1

### ISSUE THREAD

**Issue by chaoyoung** [WangJi92/arthas-idea-plugin#115]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.wangji92.arthas.plugin.action.arthas.ArthasShellScriptCommandAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.wangji92.arthas.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by WangJi92** [comment]
没有使用这个高的版本，这个影响使用？

https://github.com/carlrobertoh/CodeGPT/issues/400   
https://github.com/bazelbuild/intellij/issues/5993  

我本地 2021的版本都没有这个函数

**Comment by chaoyoung** [comment]
> 没有使用这个高的版本，这个影响使用？
> 
> ```
> https://github.com/carlrobertoh/CodeGPT/issues/400   
> https://github.com/bazelbuild/intellij/issues/5993   
> ```
> 
> 我本地 2021的版本都没有这个函数

经常提示报错，影响啊。就算清除掉，还会提示。

**Comment by WangJi92** [comment]
https://plugins.jetbrains.com/docs/intellij/basic-action-system.html#principal-implementation-overrides

**Comment by WangJi92** [comment]
java.lang.Throwable: Thread context was already set: [ComponentManager(ProjectImpl@1141896172), CoroutineName(com.github.wangji92.arthas.plugin.action.arthas.ArthasShellScriptCommandAction#actionPerformed@EditorPopup), CoroutineId(13443), "com.github.wangji92.arthas.plugin.action.arthas.ArthasShellScriptCommandAction#actionPerformed@EditorPopup#13443":StandaloneCoroutine{Active}@42f5fdb4, ModalityState.NON_MODAL, ActionContextElement(ArthasShellScriptCommandAction@EditorPopup)]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.concurrency.ThreadContext$installThreadContext$1.invoke(threadContext.kt:126)
	at com.intellij.concurrency.ThreadContext$installThreadContext$1.invoke(threadContext.kt:124)
	at com.intellij.concurrency.ThreadContext.withThreadLocal(threadContext.kt:180)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:124)
	at com.intellij.concurrency.ThreadContext.installThreadContext$default(threadContext.kt:123)
	at com.intellij.openapi.actionSystem.impl.CapturingListener.run(ActionManagerImpl.kt:1342)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.runListenerAction(ActionManagerImpl.kt:1354)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$runListenerAction(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.tick(ActionManagerImpl.kt:1287)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.access$tick(ActionManagerImpl.kt:1230)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer$2$1$1.invokeSuspend(ActionManagerImpl.kt:1260)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)

**Comment by WangJi92** [comment]
> java.lang.Throwable: Thread context was already set: [ComponentManager(ProjectImpl@1141896172), CoroutineName(com.github.wangji92.arthas.plugin.action.arthas.ArthasShellScriptCommandAction#actionPerformed@EditorPopup), CoroutineId(13443), "com.github.wangji92.arthas.plugin.action.arthas.ArthasShellScriptCommandAction#actionPerformed@EditorPopup#13443":StandaloneCoroutine{Active}@42f5fdb4, ModalityState.NON_MODAL, ActionContextElement(ArthasShellScriptCommandAction@EditorPopup)] at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376) at com.intellij.concurrency.ThreadContext$installThreadContext$1.invoke(threadContext.kt:126) at com.intellij.concurrency.ThreadContext$installThreadContext$1.invoke(threadContext.kt:124) at com.intellij.concurrency.ThreadContext.withThreadLocal(threadContext.kt:180) at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:124) at com.intellij.concurrency.ThreadContext.installThreadContext$default(threadContext.kt:123) at com.intellij.openapi.actionSystem.impl.CapturingListener.run(ActionManagerImpl.kt:1342) at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.runListenerAction(ActionManagerImpl.kt:1354) at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$runListenerAction(ActionManagerImpl.kt:1) at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.tick(ActionManagerImpl.kt:1287) at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.access$tick(ActionManagerImpl.kt:1230) at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer$2$1$1.invokeSuspend(ActionManagerImpl.kt:1260) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)

```java
 SwingUtilities.invokeLater(() ->{
            ArthasShellScriptCommandDialog dialog = new ArthasShellScriptCommandDialog(event);
            dialog.open("Quickly Get Available Command(shell command or common command)");
        }); 
```

**Comment by WangJi92** [comment]
#118

**Comment by WangJi92** [comment]
@chaoyoung 升级一下版本 ，2.45 已经支持
