### ISSUE TITLE
com.intellij.diagnostic.PluginException

### ISSUE THREAD

**Issue by thanse3** [WangJi92/arthas-idea-plugin#121]
idea version：2024.1
异常信息：
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.wangji92.arthas.plugin.action.arthas.ArthasShellScriptCommandAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.wangji92.arthas.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
<img width="824" alt="image" src="https://github.com/WangJi92/arthas-idea-plugin/assets/147324389/ca463155-8730-4416-9d76-4d74a55f29ce">

**Comment by WangJi92** [comment]
#115  重复问题，这个问题已经解决了，还没发布版本

**Comment by WangJi92** [comment]
@thanse3 升级一下版本 ，2.45 已经支持
