### ISSUE TITLE
java.lang.ClassCastException: class com.intellij.psi.PsiWildcardType cannot be cast to class com.intellij.psi.PsiClassType 

### ISSUE THREAD

**Issue by WangJi92** [WangJi92/arthas-idea-plugin#130]
java.lang.ClassCastException: class com.intellij.psi.PsiWildcardType cannot be cast to class com.intellij.psi.PsiClassType (com.intellij.psi.PsiWildcardType and com.intellij.psi.PsiClassType are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6119a835)
	at com.github.idea.json.parser.PsiParserToJson.parseVariableValue(PsiParserToJson.java:343)
	at com.github.idea.json.parser.PsiParserToJson.parseClass(PsiParserToJson.java:162)
	at com.github.idea.json.parser.PsiParserToJson.parseVariableValue(PsiParserToJson.java:406)
	at com.github.idea.json.parser.PsiParserToJson.parseClass(PsiParserToJson.java:162)
	at com.github.idea.json.parser.PsiParserToJson.parseVariableValue(PsiParserToJson.java:406)
	at com.github.idea.json.parser.PsiParserToJson.toJSONString(PsiParserToJson.java:53)
	at com.github.idea.json.parser.PsiParserToJson.toJSONString(PsiParserToJson.java:71)
	at com.github.idea.json.parser.action.CopyJsonAction.actionPerformed(CopyJsonAction.java:67)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:305)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks$lambda$4(ActionUtil.kt:276)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1161)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.kt:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction$lambda$5(ActionMenuItem.kt:269)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.kt:260)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem._init_$lambda$0(ActionMenuItem.kt:71)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed$lambda$4(ActionMenuItem.kt:102)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.kt:101)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:525)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)

**Comment by WangJi92** [comment]
接续  private Class<? extends LanguageDriver> defaultScriptingLanguageDriver;    private Class<?> typeAliasesSuperType; 报错
