### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by WangJi92** [WangJi92/arthas-idea-plugin#131]
java.lang.StackOverflowError
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:163)
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.createHardKey(ConcurrentWeakKeySoftValueHashMap.java:201)
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.get(ConcurrentWeakKeySoftValueHashMap.java:210)
	at com.intellij.psi.impl.source.resolve.ResolveCache$2.get(ResolveCache.java:108)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:201)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:174)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:854)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:846)
	at com.intellij.psi.impl.PsiImplUtil.multiResolveImpl(PsiImplUtil.java:822)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.multiResolve(PsiJavaCodeReferenceElementImpl.java:426)
	at com.intellij.psi.impl.source.PsiJavaCodeReferenceElementImpl.advancedResolve(PsiJavaCodeReferenceElementImpl.java:420)
	at com.intellij.psi.impl.source.PsiClassReferenceType.resolveGenerics(PsiClassReferenceType.java:183)
	at com.intellij.psi.util.PsiUtil.captureToplevelWildcards(PsiUtil.java:845)
	at com.intellij.psi.util.PsiUtil.equalOnEquivalentClasses(PsiUtil.java:684)
	at com.intellij.psi.PsiClassType.equals(PsiClassType.java:106)
	at java.base/java.util.HashMap.getNode(HashMap.java:570)
	at java.base/java.util.HashMap.get(HashMap.java:556)
	at com.github.idea.json.parser.toolkit.model.JPsiTypeContext.getCache(JPsiTypeContext.java:61)

**Comment by WangJi92** [comment]
案列 ： org.mybatis.spring.boot.autoconfigure.MybatisProperties  内部多层循环依赖 Configuration
