### ISSUE TITLE
An exception occurs in IDEA 2024.2.4

### ISSUE THREAD

**Issue by yinhaox** [WangJi92/arthas-idea-plugin#155]
arthas idea version is 2.26

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.wangji92.arthas.plugin.action.arthas.ArthasWatchCommandAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.wangji92.arthas.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by WangJi92** [comment]
@yinhaox 升级升级 ，你这个版本太老了 ，最新都 2.48 了

**Comment by WangJi92** [comment]
![image](https://github.com/user-attachments/assets/648d4e81-b465-4cc2-b0c8-2309e52e0568)
