### ISSUE TITLE
Idea redefine 菜单报错

### ISSUE THREAD

**Issue by tomatofrommars** [WangJi92/arthas-idea-plugin#63]
插件版本：2.32
idea版本：2021.2.3(Ultimate Edition) Build #IU-212.5457.46
mac版本：macOS 10.15.7

redefine 是我用的最多的功能了，每次使用都会报个错出来。
有时候生成的脚本执行以后也不生效，没有成功替换。
![企业微信截图_dd8f2660-eabd-458b-92df-b9de3fe66fec](https://user-images.githubusercontent.com/16113120/143185294-e814251a-87a9-47bb-9536-3cff8303de7a.png)

报错
```
Do not request resource from classloader using path with leading slash

com.intellij.diagnostic.PluginException: /template/arthas-idea-plugin-hot-swap.sh [Plugin: com.github.wangji92.arthas.plugin]
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:472)
	at com.intellij.ide.plugins.cl.PluginClassLoader.getResourceAsStream(PluginClassLoader.java:462)
	at com.github.wangji92.arthas.plugin.utils.IoUtils.getResourceFile(IoUtils.java:29)
	at com.github.wangji92.arthas.plugin.utils.StringUtils.stringSubstitutorFromFilePath(StringUtils.java:39)
	at com.github.wangji92.arthas.plugin.action.arthas.ArthasHotRedefineCommandAction.lambda$actionPerformed$3(ArthasHotRedefineCommandAction.java:173)
	at com.intellij.openapi.application.WriteAction.lambda$runAndWait$2(WriteAction.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:950)
	at com.intellij.openapi.application.WriteAction.compute(WriteAction.java:104)
	at com.intellij.openapi.application.WriteAction.lambda$computeAndWait$3(WriteAction.java:153)
	at com.intellij.openapi.application.WriteThread.lambda$submit$0(WriteThread.java:28)
	at com.intellij.openapi.application.WriteThread.lambda$submit$1(WriteThread.java:45)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLaterOnWriteThread$10(ApplicationImpl.java:783)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by WangJi92** [comment]
https://github.com/JetBrains/spotbugs-intellij-plugin/issues/66

**Comment by WangJi92** [comment]
@tomatofrommars 人在？ 可以 给我调试一下  加我钉钉好友  我给你包

**Comment by WangJi92** [comment]
2.34 已修复 2021.3 已经验证
